# Generated by Django 4.2.4 on 2023-08-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userprofiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(default="null", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(default="null", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.CharField(default="null", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(default="null", max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(default="null", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="zipcode",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
