# Generated by Django 4.2.4 on 2023-08-26 00:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="favourites",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="favourite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
