# Generated by Django 4.2.4 on 2023-08-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_item_favourites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.FloatField(),
        ),
    ]
